-- ==============================================================
-- คำสั่งสร้างตารางสำหรับระบบพัสดุและครุภัณฑ์โรงเรียนดงกลาง บน Supabase (PostgreSQL)
-- สามารถคัดลอกคำสั่งทั้งหมดนี้ไปวางในเมนู SQL Editor บน Supabase แล้วกด RUN ได้ทันที
-- ==============================================================

-- 1. ตารางทะเบียนคุมครุภัณฑ์ (assets)
CREATE TABLE IF NOT EXISTS public.assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_code TEXT,
  received_date TEXT,
  asset_name TEXT,
  spec TEXT,
  doc_no TEXT,
  cost NUMERIC DEFAULT 0,
  useful_life INTEGER DEFAULT 5,
  location TEXT,
  status TEXT DEFAULT 'ใช้งานได้ดี',
  vendor TEXT,
  responsible_person TEXT,
  department TEXT,
  remark TEXT,
  category TEXT DEFAULT 'ครุภัณฑ์คอมพิวเตอร์',
  model TEXT,
  qty INTEGER DEFAULT 1,
  vendor_address TEXT,
  vendor_phone TEXT,
  budget_source TEXT DEFAULT 'เงินงบประมาณ',
  acquisition_method TEXT DEFAULT 'เฉพาะเจาะจง',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 2. ตารางบัญชีคุมวัสดุ (materials)
CREATE TABLE IF NOT EXISTS public.materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trans_date TEXT,
  material_code TEXT,
  material_name TEXT,
  size_spec TEXT,
  unit TEXT,
  party TEXT,
  doc_no TEXT,
  budget_type TEXT,
  opening_stock INTEGER DEFAULT 0,
  qty_in INTEGER DEFAULT 0,
  qty_out INTEGER DEFAULT 0,
  unit_price NUMERIC DEFAULT 0,
  remark TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 3. ตารางการตั้งค่าระบบและรหัสผ่าน (system_settings)
CREATE TABLE IF NOT EXISTS public.system_settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 4. เปิดสิทธิ์การเข้าถึง (Row Level Security - RLS Policies) เพื่อให้ API จัดการได้
ALTER TABLE public.assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all operations on assets" ON public.assets FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on materials" ON public.materials FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations on system_settings" ON public.system_settings FOR ALL USING (true) WITH CHECK (true);
